// POYLFILLS 

// A Polyfills is a piece of code that provides functionality that is not built into a browser by default. Polyfills are typically used to implement the feature of newwer javascript standards in old browsers that doesn't support those features



//Transpilers(source to source compiler)

// A Transpiler is a tool that translates the code written in onde version of pergrommging langugae into another. Example Babel';

// const add=(a,b)=>a+b ; not support in es6 

var add=function(a,b){
    return a+b;
};

// by using bebel it will convert intp same format 