// SOME METHODS HELP US TO KNOW IS THERE SOME VALUE IN THE GIVEN OPTION
// IT ALSO RETURN IN THE FORM OF BOOLEAN


const movements = [200, 450, -400, 3000, -650, -130, 70, 1300];

// const anyDeposits=movements.some(mov=>mov>5000);
// console.log(anyDeposits);


// The difference between include methods and some method is that :

// Some : You can do this by puting in an Condition 
// Inclue: it is based on EQUALITY
