// use <database-name> 
// it create database and switch to it if it alreadt not exist otherwise it simple get switched 

// Note: You have to choose collection name by yourself

// db.<collectionname>.insertOne({})  ---> TO INSERT A SINGLE DOCUMENT RECORD IN IT WITH THE COLLECTION NAME 
// db.<collectionname>.insertMany([{},{},{}]) ---> TO INSERT A MANY DOCUMENT RECORD IN IT WITH THE COLLECTION NAME

//db.<collectioname>.find() ==> IS USED TO SEE THE RECORD THAT YOU HAVE INSERTED IT 

// show dbs -> help us to show all the database 

// show collections - to showcase all the collection realted to current database

// ONE THING MORE I WANT TO ADD ONE THING THAT IT IS NOT NECESSARY TO WRITE EVERY PROPERTY IN EACH AND EVERY DOCUMENTS 
