//  it is a non-sql database

// IN MONGODB WE CAN SAY THAT IT CAN CONTAIN ONE OR MORE COLLECTION 

// YOU CAN THINK COLLECTION AS A TABLE OF DATA 

// EACH COLLECTION CAN CONTAIN ONE OR MORE DATA STRUCTURES CALLED DOCUMENTS 

// A DOCUMENT WOULD BE ROW IN A TABLE

// EACH DOCUMENT CONTAION DATA ABOUT A SINGLE ENTITY

//A COLLECTION IS LIKE A PARENT STRUCTURE THAT CONTAIN ALL THESE ENTITIES



// MONGODB IS A DOCUMENT DATABASE WITH THE SCALABILITY AND FLEXBILITY THAT YOU WANT WITH QUERYING AND INDEXING THAT YOU NEED

// FEATURES 

// DOCUMENT BASED  ::  MONGODB STORES THE DATA IN DOCUMENTS (FIELD-VALUED PAIR DATA STRUCTURES , NOSQL)
// SCALABLE :: VERY EASY TO DISTRIBUTE DATA ACCROSS MULTIPLE MACHINES AS YOUR USERS AND AMOUNT OF DATA GROWS 
// FLEXIBLE :: NO DOCUMENT DATA SCHEMA IS REQUIRED SO EACH DOCUMENT CAN HAVE DIIFFERENT NUMBER AND TYPE OF FIELDS 
// PERFORMANT :: EMBEDDED DATA MODELS , INDEXING , SHRADING , FLEXIBLE DOCUMENTS NATIVE DUPLICATIONS ETC 
// FREE AND OPEN SOURCE PUBLISHES UNDER SSPL LISCENCE

// MONGODB USES A DATA FORMAT SIMILAR TO JSON FOR DATA STORAGE CALLED BSON 

// EMBEDED DOCUMENT IS POSSSIBLE IN MONGODB SOMETHING THAT IS NOT POSSIBLE IN RELATIONAL DATABASE 

// EMBEDDING / NORMALIZING :: INCLUDIN RELATED INTO AN SINGLE DOCUMENT THIS ALLOWS FOR QUICKER ACCESS AND EASIER DATA MODELS (IT'S NOT THE BEST SOLTUION THOUFHT)

//FIND THE MAXIMUM SIZE OF EACH DOCUMENT IS CURRENTLY 16MB BUT THIS MIGHT INCREASE IN AN FUTURE 

// EACH DOCUEMNTS CONTAION UNIQUE ID WHICH ACT AS PRIMARY KEY OF DOCUMENT AND IT AUTOMATICALLY GENREREATEED WITH OBJECT ID DATA TYPE 

