function getInfo(){
    if(firstname.length>10){
        console.log("Your First Name Has been Accepted Successfully");
    }
    else{
        console.log("Soory Your First Name has been enterd Wrong");
    }
}


getInfo();



//COMPILE TIME -> MEANS WHEN YOU ARE WRITING THE CODE 
// RUN TIME -> MEANS WHEN YOU ARE RUNNING THE CODE 

// SO IN TYPESCRIPT IT HELP US TO IDENTIFY THE ERROR DURING THE COMPILE TIME ONLY WHERE AS JAVASCRIPT IS UNABLE TO IDENTIFY THE ERROR DURING THE COMPILE TIME 
// SO IT CAN BE ABLE TO DETECT THE ERROR DURING RUN TIME ONLY 

// LIKE IN THE ABOVE EXAMPLE THAT "firstname.length" ALREADY UNDELINE WITH RED LINE THAT IT HAS SOME ERROR WHERE AS WHEN YOU WRITE SAME CODE IN JAVASCRIPT IT WILL DISPLAY ANY ERROR 
// IN JAVASCRIPT

// IT ALSO GIVE US THE FLEXIBILITY OF WRITE CODE IN OBJECT-ORIENTED PROGARMMING WAY IN MORE DETAIL MANNER


